# Generated by Django 4.1.4 on 2022-12-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.freepik.es%2Ffotos-vectores-gratis%2Ffondo&psig=AOvVaw3Z0Z0Z0Z0Z0Z0Z0Z0Z0Z0Z&ust=1634040000000000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCJjX2fjX3vMCFQAAAAAdAAAAABAD', max_length=2083),
        ),
    ]
